# -*- coding: utf-8 -*-
"""WithLLM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12NJC-a3ruaz-jrK_3Xj0aYw1KOIOyryR

# **🤖 Quora Question Pair Similarity Detection**

### *Semantic Similarity using BERT & Siamese Networks*

**Project Overview**
This project tackles the **Paraphrase Detection** task using the Quora Question Pairs dataset. The goal is to determine if two questions have the same intent/meaning. This is a critical problem in NLP with applications in:

* **Forum Moderation:** Reducing duplicate content.
* **Customer Support:** Automatically routing similar queries to existing FAQs.
* **Search Engine Optimization:** Canonicalizing content.

**Technical Approach**
We explore two distinct state-of-the-art approaches using **Transfer Learning**:

1. **Cross-Encoder (Binary Classification):** Fine-tuning a BERT-based model (`all-MiniLM-L6-v2`) with a classification head to predict a binary label (0 or 1).
2. **Bi-Encoder (Sentence Transformers):** Training a Siamese Network with **Contrastive Loss** to generate semantically meaningful sentence embeddings, where similar questions are close in vector space.

---

## 1. Environment Setup

We rely on the Hugging Face ecosystem (`transformers`, `datasets`, `sentence-transformers`) for model architectures and `torchmetrics` for tracking classification performance.

---
"""

!pip install torchmetrics

import pandas as pd#from transformers import
from sentence_transformers import SentenceTransformer, util
from sklearn.model_selection import train_test_split
from datasets import Dataset
from transformers import  AutoTokenizer,AutoModelForSequenceClassification
import torch
from tqdm.auto import tqdm
from torchmetrics import Accuracy
from torch.optim.lr_scheduler import LambdaLR
from torch.utils.data import DataLoader
from torch.optim import AdamW
import torch.nn as nn
import matplotlib.pyplot as plt
from torch.utils.data import DataLoader

"""## 2. Data Ingestion & Preprocessing

The dataset consists of question pairs labelled as `is_duplicate` (1) or not (0).

* **Data Cleaning:** We remove rows with missing values to ensure stability.
* **Time Based Split :** We split the data into training (80%) and testing (20%) sets. Crucially, we use a **Time Based split** to preventing data leakage or bias.
"""

df=pd.read_csv("train.csv")

df.head()

df.isnull().sum()

df.duplicated().sum()

df=df.dropna()

df1=df.drop(["id","qid1","qid2"],axis=1)

train_df, test_df = train_test_split(
    df[["question1", "question2", "is_duplicate"]],
    test_size=0.2,
    stratify=df["is_duplicate"],
    random_state=42
)

train_hf = Dataset.from_pandas(train_df)
test_hf  = Dataset.from_pandas(test_df)

"""## 3. Tokenization & Data Pipeline

Deep Learning models cannot process raw text. We must convert text into numerical tokens.

* **Tokenizer:** We use `bert-base-cased`.
* **Padding & Truncation:** We standardize sequence lengths to `128` tokens. This ensures efficient batch processing on the GPU.
* **PyTorch DataLoaders:** We convert the processed text into PyTorch tensors and wrap them in DataLoaders to handle batching and shuffling during training.
"""

tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")

def tokenize_function(examples):
    return tokenizer(
        examples["question1"],
        examples["question2"],
        padding="max_length",
        truncation=True,
        max_length=128
    )

train_tokenized = train_hf.map(
    tokenize_function,
    batched=True,
    remove_columns=["question1", "question2"]
)

test_tokenized = test_hf.map(
    tokenize_function,
    batched=True,
    remove_columns=["question1", "question2"]
)

train_tokenized = train_tokenized.rename_column(
    "is_duplicate", "labels"
)

test_tokenized = test_tokenized.rename_column(
    "is_duplicate", "labels"
)

if "__index_level_0__" in train_tokenized.column_names:
    train_tokenized = train_tokenized.remove_columns(["__index_level_0__"])
if "__index_level_0__" in test_tokenized.column_names:
    test_tokenized = test_tokenized.remove_columns(["__index_level_0__"])

train_tokenized.set_format("torch")
test_tokenized.set_format("torch")

# Create a training data loader
train_dataloader = DataLoader(train_tokenized, shuffle=True, batch_size=16)

# Create an evaluation data loader
eval_dataloader = DataLoader(test_tokenized, batch_size=16)

train_dataloader

"""## 4. Approach 1: Cross-Encoder Classification

In this approach, we feed *both* questions simultaneously into the model, separated by a special `[SEP]` token. The model's self-attention mechanism attends to both questions at once, allowing it to capture deep interaction features.

* **Architecture:** `all-MiniLM-L6-v2` (a distilled, efficient version of BERT) with a linear classification layer on top.
* **Pros:** Highly accurate because the model sees the interaction between words in both sentences.
* **Cons:** Computationally expensive for search (O(n^2) complexity), as every pair must be processed.
"""

model_name = "sentence-transformers/all-MiniLM-L6-v2"
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=2)

device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
model.to(device)

def get_bert_report(model, dataloader, device):
    # 1. Prepare
    model.eval()  # Set to evaluation mode
    all_preds = []
    all_labels = []

    print("⏳ Evaluating BERT model...")

    # 2. Loop through data (No Gradients needed)
    with torch.no_grad():
        for batch in tqdm(dataloader):
            # Move batch to GPU
            batch = {k: v.to(device) for k, v in batch.items()}

            # Forward pass
            outputs = model(**batch)

            # 3. Get Predictions
            # BERT outputs 'logits' (raw scores).
            # We take the standard argmax: Class 0 (Not Duplicate) or Class 1 (Duplicate)
            logits = outputs.logits
            preds = torch.argmax(logits, dim=-1)

            # Store results
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(batch["labels"].cpu().numpy())

    # 4. Generate Report
    print("\n📊 BERT Classification Report:")
    print(classification_report(all_labels, all_preds))

    return all_preds

predictions = get_bert_report(model, eval_dataloader, device)

"""We implement a custom training loop using **PyTorch**:

* **Optimizer:** `AdamW` (Adam with Weight Decay) is used for stable convergence.
* **Loss Function:** The model outputs `logits`. We use standard **Cross-Entropy Loss** (calculated internally by the Hugging Face model) to penalize incorrect class predictions.
* **Gradient Descent:** We iterate through the data, calculate gradients, and update model weights.

"""

def train_model(model, train_dataloader, num_epochs):
    optimizer = AdamW(model.parameters(), lr=2e-5)
    tr_losses = []

    print("🚀 Starting Fast Training...")
    model.train()

    for epoch in range(num_epochs):
        loop = tqdm(train_dataloader, leave=True)
        total_loss = 0

        for batch in loop:
            batch = {k: v.to(device) for k, v in batch.items()}

            optimizer.zero_grad()

            outputs = model(**batch)   # labels included
            loss = outputs.loss        # <-- THIS is key

            loss.backward()
            optimizer.step()

            total_loss += loss.item()
            loop.set_description(f"Epoch {epoch+1}")
            loop.set_postfix(loss=loss.item())

        avg_loss = total_loss / len(train_dataloader)
        tr_losses.append(avg_loss)

    print("✅ Training complete.")
    plt.plot(tr_losses)
    plt.xlabel("Epochs")
    plt.ylabel("Loss")
    plt.show()

train_model(model,train_dataloader,2)

torch.save(model, 'my_model.pt')

"""### 4.2 Threshold Tuning

Standard classification uses a threshold of `0.5` (Argmax). However, for imbalanced datasets or specific business requirements (e.g., minimizing False Positives), tuning the decision threshold is vital.

* We analyze probabilities on the test set to find the **optimal threshold** that maximizes Accuracy or F1-Score.
"""

import torch
import torch.nn.functional as F
import numpy as np
from sklearn.metrics import accuracy_score, classification_report
from tqdm.auto import tqdm

def tune_bert_threshold(model, dataloader, device):
    model.eval()
    all_probs = []
    all_labels = []

    print("⏳ Collecting probabilities from BERT...")

    with torch.no_grad():
        for batch in tqdm(dataloader):
            batch = {k: v.to(device) for k, v in batch.items()}

            outputs = model(**batch)
            logits = outputs.logits

            # 1. Convert Logits to Probabilities (0 to 1) using Softmax
            probs = F.softmax(logits, dim=-1)

            # We only care about the probability of being Class 1 (Duplicate)
            # This extracts the second column
            class_1_probs = probs[:, 1].cpu().numpy()

            all_probs.extend(class_1_probs)
            all_labels.extend(batch["labels"].cpu().numpy())

    # 2. Find the Best Threshold
    all_probs = np.array(all_probs)
    all_labels = np.array(all_labels)

    best_acc = 0
    best_thresh = 0.5

    # Check thresholds from 0.1 to 0.9
    print("\n🔎 Searching for the best threshold...")
    for thresh in np.arange(0.1, 0.95, 0.05):
        preds = (all_probs > thresh).astype(int)
        acc = accuracy_score(all_labels, preds)

        # Print only if it improves
        if acc > best_acc:
            best_acc = acc
            best_thresh = thresh
            print(f"✨ New Best: Threshold {thresh:.2f} -> Accuracy {acc:.4f}")

    print(f"\n🏆 WINNER: Threshold {best_thresh:.2f}")

    # 3. Generate Final Report with the Winner
    final_preds = (all_probs > best_thresh).astype(int)
    print("\n" + classification_report(all_labels, final_preds))

# Run it
tune_bert_threshold(model, eval_dataloader, device)

"""## 5. Approach 2: Bi-Encoder (Siamese Network)

While the Cross-Encoder is accurate, it is slow for retrieval tasks. Here, we train a **Sentence Transformer** (Bi-Encoder).

* **Architecture:** Two identical BERT networks (sharing weights) process each question *independently*.
* **Output:** Each question is converted into a fixed-size vector (embedding).
* **Pros:** Extremely fast for search. We can pre-compute embeddings and find duplicates using **Cosine Similarity** in milliseconds.
"""

# 1. Load a FRESH, Untrained model
print("⏳ Loading raw pre-trained model (No Fine-Tuning)...")
raw_model = SentenceTransformer('all-MiniLM-L6-v2')

# 2. Encode Test Data (Same test_df as before)
# We use the same data to make it a fair comparison
print("⏳ Computing embeddings...")
q1_raw = raw_model.encode(test_df['question1'].astype(str).tolist(),
                          batch_size=64, convert_to_tensor=True, show_progress_bar=True)
q2_raw = raw_model.encode(test_df['question2'].astype(str).tolist(),
                          batch_size=64, convert_to_tensor=True, show_progress_bar=True)

# 3. Compute Cosine Similarity
raw_scores = util.pairwise_cos_sim(q1_raw, q2_raw)

# 4. Check Performance
# We'll use a standard threshold of 0.75 for the raw model
# (Raw models often need a slightly lower threshold than fine-tuned ones)
raw_threshold = 0.75
raw_preds = (raw_scores > raw_threshold).float().cpu().numpy().astype(int)

# 5. Print Results
print("\n📉 Performance WITHOUT Fine-Tuning:")
print(f"Accuracy: {accuracy_score(test_labels, raw_preds):.4f}")
print("-" * 30)
print(classification_report(test_labels, raw_preds))

model = SentenceTransformer("all-MiniLM-L6-v2")

"""### 5.1 Metric Learning with Contrastive Loss

Instead of simple classification, we use **Contrastive Loss**.

* **Concept:** The loss function pulls the embeddings of duplicate questions *closer together* (minimizing distance) and pushes non-duplicate questions *farther apart*.
* **Result:** The model learns a semantic vector space where distance equals meaning.
"""

from sentence_transformers import SentenceTransformer, InputExample, losses
from torch.utils.data import DataLoader


# 2. Prepare Data (The library needs a specific format)
# We convert your DataFrame rows into 'InputExample' objects
train_examples = []
for i, row in train_df.iterrows():
    train_examples.append(InputExample(
        texts=[str(row['question1']), str(row['question2'])],
        label=float(row['is_duplicate']) # Must be float for some loss functions
    ))

# 3. Create DataLoader (Batch size 32 or 64 works great on T4)
train_dataloader = DataLoader(train_examples, shuffle=True, batch_size=32)

# 4. Use Contrastive Loss (The Gold Standard for Duplicates)
# This loss pulls duplicate questions close and pushes non-duplicates apart.
train_loss = losses.ContrastiveLoss(model=model)

# 5. Train (1 Epoch is usually enough for MiniLM on this data)
print("🚀 Training started... this handles everything automatically.")
model.fit(
    train_objectives=[(train_dataloader, train_loss)],
    epochs=1,
    warmup_steps=100,
    show_progress_bar=True
)

# 6. Save it
model.save("my_duplicate_model")
print("✅ Done! Model saved.")

"""### 5.2 Evaluation: Cosine Similarity

To evaluate the Bi-Encoder, we don't use a classifier head. Instead, we compute the **Cosine Similarity** between the embeddings of Question 1 and Question 2.

* If Similarity > Threshold, they are duplicates.
* We again tune this threshold to maximize performance on the test set.
"""

from sklearn.metrics import accuracy_score
import numpy as np

# 1. Compute all Similarity Scores (if you haven't already)
# (Assuming 'cosine_scores' is still in memory from the previous step)
scores = cosine_scores.cpu().numpy() # Convert to numpy array
labels = test_labels

# 2. Loop to find the Best Threshold
best_acc = 0
best_threshold = 0.5

# Check thresholds from 0.50 to 0.95
for thresh in np.arange(0.5, 0.95, 0.05):
    preds = (scores > thresh).astype(int)
    acc = accuracy_score(labels, preds)

    print(f"Threshold {thresh:.2f} --> Accuracy: {acc:.4f}")

    if acc > best_acc:
        best_acc = acc
        best_threshold = thresh

print(f"\n🚀 BEST RESULT: Threshold {best_threshold:.2f} gives Accuracy {best_acc:.4f}")

# 3. Generate Final Report with Best Threshold
final_preds = (scores > best_threshold).astype(int)
print(classification_report(labels, final_preds))

!jupyter nbconvert --to html WithLLM.ipynb

"""## 6. Model Deployment (Interactive Demo)

A model is only useful if it can be consumed. We use **Gradio** to create a web-based interface for our model.

* **User Input:** Accepts two text strings.
* **Backend:** Runs the trained Sentence Transformer to generate embeddings and calculates similarity.
* **Output:** Returns a "Duplicate" or "Not Duplicate" label along with the confidence score.

This step demonstrates the ability to move a model from **Research** (Notebook) to **Production** (Application).
"""

import shutil

# Zip the folder 'my_duplicate_model' into a file named 'my_duplicate_model.zip'
shutil.make_archive('my_duplicate_model', 'zip', 'my_duplicate_model')

print("✅ Ready! Refresh the file browser on the left and look for 'my_duplicate_model.zip'")

from sentence_transformers import SentenceTransformer

# Load directly from the folder
model = SentenceTransformer('my_duplicate_model')

!pip install gradio

import gradio as gr
from sentence_transformers import util

# 1. Define the Logic (Returns 2 items: Label AND Score)
def predict_duplicate(question1, question2):
    # Wrap inputs in lists for the model
    emb1 = model.encode([question1], convert_to_tensor=True)
    emb2 = model.encode([question2], convert_to_tensor=True)

    # Calculate similarity
    score = util.pairwise_cos_sim(emb1, emb2).item()

    # Decision Logic (Using your 0.75 threshold)
    threshold = 0.75
    label = "✅ DUPLICATE" if score > threshold else "❌ NOT DUPLICATE"

    # Return TWO values
    return label, float(score)

# 2. Create the App Interface (Must match the 2 outputs above)
interface = gr.Interface(
    fn=predict_duplicate,
    inputs=[
        gr.Textbox(lines=2, placeholder="Type Question 1 here..."),
        gr.Textbox(lines=2, placeholder="Type Question 2 here...")
    ],
    outputs=[
        gr.Label(label="Prediction"),         # Output 1
        gr.Number(label="Similarity Score")   # Output 2
    ],
    title="🤖 Quora Duplicate Detector",
    description="Enter two questions to see if they are semantically the same.",
    examples=[
        ["How can I learn Python?", "What is the best way to start coding in Python?"],
        ["How do I cook pasta?", "Why is the sky blue?"]
    ]
)

# 3. Launch it once
interface.launch(share=True, debug=True)